namespace SamSWAT.FireSupport.ArysReloaded.Unity.Vehicles
{
    public enum VoiceoverType
    {
        StationReminder,
        StationAvailable,
        StationDoesNotHear,
        StationStrafeRequest,
        StationStrafeEnd,
        StationExtractionRequest,
        StationApacheRequest,
        StationApacheEnd,
        JetArriving,
        JetFiring,
        JetLeaving,
        SupportHeliArriving,
        SupportHeliArrivingToPickup,
        SupportHeliPickingUp,
        SupportHeliHurry,
        SupportHeliLeaving,
        SupportHeliLeavingAfterPickup,
        SupportHeliLeavingNoPickup,
        ApacheArriving,
        ApacheFiringM230,
        ApacheFiringRockets,
        ApacheConfirmKills,
        ApachePause,
        ApacheLeaving,
        ApacheTakingFire,
        ApacheReceivingDamage,
        ApacheCrashing
    }
}
